<a href="https://colab.research.google.com/github/jaeduck223/bigdata/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_5%EC%A3%BC%EC%B0%A8_1%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [ ]:
pd.unique(values)  #하나의 열에서 특정 값이 반복되는 경우, 유일값 추출

array(['apple', 'orange'], dtype=object)

In [ ]:
pd.value_counts(values)#하나의 열에서 특정 값이 반복되는 경우, 반복되는 횟수 추출

<ipython-input-4-1f11d3b14906>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)#하나의 열에서 특정 값이 반복되는 경우, 반복되는 횟수 추출


apple     6
orange    2
Name: count, dtype: int64

In [ ]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])

In [ ]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [ ]:
dim

0     apple
1    orange
dtype: object

In [ ]:
dim.take(values) #take 메서드를 사용하면, Series에 저장된 원래 문자열을 구할 수 있다.
# 이러한 표현을 범주형 표기법이라 한다.

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [ ]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
#NumPy 버전 1.17부터 추가된 새로운 난수 생성기(Generator)이다. random.seed에 비해 다양한 난수분포를 가질 수 있고,
#여러개의 난수를 관리하는 등 강력한 기능을 제공
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   basket_id  8 non-null      int64  
 1   fruit      8 non-null      object 
 2   count      8 non-null      int64  
 3   weight     8 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes


In [ ]:
fruit_cat = df['fruit'].astype('category') #범주형 데이터로 변경
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [ ]:
c = fruit_cat.array #.array 속성으로 접근, fruit_cat은 pandas.Categorical 인스턴스이다.
type(c)
#Categorical객체에는 categories와 code 속성이 있다.

pandas.core.arrays.categorical.Categorical

In [ ]:
c.categories  #categories 속성

Index(['apple', 'orange'], dtype='object')

In [ ]:
c.codes      # code 속성

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [ ]:
df['fruit'] = df['fruit'].astype('category')  #DataFrame의 열을 범주형으로 변경
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [ ]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar']) #파이썬 시퀀스에서 pandas.Categorical을 직접 생성
my_categories
#my_categories.codes
#my_categories.categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [ ]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)  #기존에 정의된 categories와 code가 있다면 from_codes로 생성
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [ ]:
# 범주형 변경시 순서를 보장하지 않는다. -> 순서를 지정할 수 있다.
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [ ]:
my_cats_2.as_ordered()  #순서가 없는 범주현 인스턴스는 as_ordered 매서드사용해서 정렬

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [ ]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [ ]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [ ]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [ ]:
bins = pd.Series(bins, name='quartile')
bins

0      Q1
1      Q4
2      Q1
3      Q2
4      Q2
       ..
995    Q3
996    Q3
997    Q2
998    Q3
999    Q2
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [ ]:
results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index()) #판다스 테이블 조작 방법
results

<ipython-input-24-f26870ef29f4>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index()) #판다스 테이블 조작 방법


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [ ]:
N = 10_000_000 #판다스에서는 언더바로 수를 표현해도 상관없음!
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))  #천만개의 Series

In [ ]:
labels

0          foo
1          bar
2          baz
3          qux
4          foo
          ... 
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: object

In [ ]:
categories = labels.astype('category')

In [ ]:
categories

0          foo
1          bar
2          baz
3          qux
4          foo
          ... 
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: category
Categories (4, object): ['bar', 'baz', 'foo', 'qux']

In [ ]:
labels.memory_usage(deep=True) #메모리 사이즈 비교

600000132

In [ ]:
categories.memory_usage(deep=True) #판다스에서는 종류의 개수를 판단함!

10000544

In [ ]:
%time _ = labels.astype('category') #실행 시간 측정

CPU times: user 719 ms, sys: 167 ms, total: 886 ms
Wall time: 1.24 s


In [ ]:
%timeit labels.value_counts()

545 ms ± 7.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit categories.value_counts() #범주형 데이터는 #categorical 쓰는게 좋다!

44 ms ± 488 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [ ]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
# 데이터의 실제 범주가 네 종류를 넘는다면, set_categories메서드 이용 변경
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories) #실제 카테고리에 매핑!
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [ ]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [ ]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [ ]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [ ]:
import pandas as pd

df=pd.read_csv('서울일자리센터 인재정보 직종별, 지역별 목록.csv',encoding='cp949')
df

구직신청번호 성별  나이  학력공통코드 학력공통코드명 희망근무지역(시도)_1 희망근무지역명(시군구)_1  \
0     H128202107071973  남  74  J00106    고등학교           서울            강북구   
1     H309202107071965  남  87  J00100    관계없음           서울            강북구   
2     H110202107071953  여  68  J00100    관계없음           서울            서초구   
3     H318202107071951  남  30  J00106    고등학교           서울            금천구   
4     H129202107071950  여  66  J00106    고등학교           서울            송파구   
...                ... ..  ..     ...     ...          ...            ...   
1351  H001202104121072  여  54  J00102    초등학교           서울            도봉구   
1352  H310202104090587  여  61  J00104     중학교           서울            도봉구   
1353  H001202101250403  여  47  J00110  대학_대학교           서울             전체   
1354  H001202101250036  여  47  J00108    전문대학           서울            노원구   
1355  H001202101182829  여  23  J00108    전문대학           경기            NaN   

     희망근무지역명(시도)_2 희망근무지역명(시군구)_2  희망직종공통코드  ... 희망직종경력년_월수  구직인증상태공통구분  \
0               서울            NaN    814001  ...       6년0월      J03402   
1              NaN            NaN    561100  ...         신입      J03402   
2               서울            강남구    561101  ...         신입      J03402   
3              NaN            NaN    622301  ...         신입      J03402   
4               서울            NaN    561101  ...       3년0월      J03402   
...            ...            ...       ...  ...        ...         ...   
1351            서울             전체    561101  ...         신입      J03404   
1352            서울             전체    550104  ...      10년0월      J03404   
1353            경기            광명시     27200  ...      15년0월      J03404   
1354            서울            중랑구    231101  ...       1년2월      J03402   
1355            서울            NaN    902900  ...       1년0월      J03402   

      구직인증상태공통구분명 검색키워드1 검색키워드2 검색키워드3 검색키워드4  검색키워드5     등록일시     수정일시  
0              승인    NaN    NaN    NaN    NaN     NaN  15:29.0  15:34.0  
1              승인    NaN    NaN    NaN    NaN     NaN  05:55.0  05:59.0  
2              승인    NaN    NaN    NaN    NaN     NaN  57:27.0  57:30.0  
3              승인    NaN    NaN    NaN    NaN     NaN  51:30.0  51:33.0  
4              승인    NaN    NaN    NaN    NaN     NaN  51:25.0  51:29.0  
...           ...    ...    ...    ...    ...     ...      ...      ...  
1351           알선     청소    NaN    NaN    NaN     NaN  25:40.0  39:47.0  
1352           알선    긴시간    NaN    NaN    NaN     NaN  37:31.0  19:48.0  
1353           알선   전산입력  부동산중개  컴퓨터활용   자료편집  고객민원상담  59:11.0  10:01.0  
1354           승인    NaN    NaN    NaN    NaN     NaN  10:47.0  08:06.0  
1355           승인    NaN    NaN    NaN    NaN     NaN  06:44.0  25:54.0  

[1356 rows x 23 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356 entries, 0 to 1355
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   구직신청번호          1356 non-null   object 
 1   성별              1356 non-null   object 
 2   나이              1356 non-null   int64  
 3   학력공통코드          1356 non-null   object 
 4   학력공통코드명         1356 non-null   object 
 5   희망근무지역(시도)_1    1341 non-null   object 
 6   희망근무지역명(시군구)_1  1201 non-null   object 
 7   희망근무지역명(시도)_2   1136 non-null   object 
 8   희망근무지역명(시군구)_2  448 non-null    object 
 9   희망직종공통코드        1356 non-null   int64  
 10  희망직종공통코드명       1356 non-null   object 
 11  희망직종경력년수        801 non-null    float64
 12  희망직종경력개월수       801 non-null    float64
 13  희망직종경력년_월수      1356 non-null   object 
 14  구직인증상태공통구분      1356 non-null   object 
 15  구직인증상태공통구분명     1356 non-null   object 
 16  검색키워드1          204 non-null    object 
 17  검색키워드2          141 non-null    o

In [ ]:
#7장 실습문제(1) - 1번 정답
df.drop(df.loc[:, '검색키워드1':'검색키워드5'], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356 entries, 0 to 1355
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   구직신청번호          1356 non-null   object 
 1   성별              1356 non-null   object 
 2   나이              1356 non-null   int64  
 3   학력공통코드          1356 non-null   object 
 4   학력공통코드명         1356 non-null   object 
 5   희망근무지역(시도)_1    1341 non-null   object 
 6   희망근무지역명(시군구)_1  1201 non-null   object 
 7   희망근무지역명(시도)_2   1136 non-null   object 
 8   희망근무지역명(시군구)_2  448 non-null    object 
 9   희망직종공통코드        1356 non-null   int64  
 10  희망직종공통코드명       1356 non-null   object 
 11  희망직종경력년수        801 non-null    float64
 12  희망직종경력개월수       801 non-null    float64
 13  희망직종경력년_월수      1356 non-null   object 
 14  구직인증상태공통구분      1356 non-null   object 
 15  구직인증상태공통구분명     1356 non-null   object 
 16  등록일시            1356 non-null   object 
 17  수정일시            1356 non-null   o

In [ ]:
df.rename(index= {'희망근무지역(시도)_1':'근무지역(시도)_1',
    '희망근무지역명(시군구)_1':'근무지역명(시군구)_1',
    '희망근무지역명(시도)_2':'근무지역명(시도)_2',
    '희망근무지역명(시군구)_2':'근무지역명(시군구)_2',
    '희망직종공통코드':'공통코드',
    '희망직종공통코드명':'공통코드명',
    '희망직종경력년수':'경력년수',
    '희망직종경력개월수':'경력개월수',
    '희망직종경력년_월수':'경력년_월수'}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1356 entries, 0 to 1355
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   구직신청번호          1356 non-null   object 
 1   성별              1356 non-null   object 
 2   나이              1356 non-null   int64  
 3   학력공통코드          1356 non-null   object 
 4   학력공통코드명         1356 non-null   object 
 5   희망근무지역(시도)_1    1341 non-null   object 
 6   희망근무지역명(시군구)_1  1201 non-null   object 
 7   희망근무지역명(시도)_2   1136 non-null   object 
 8   희망근무지역명(시군구)_2  448 non-null    object 
 9   희망직종공통코드        1356 non-null   int64  
 10  희망직종공통코드명       1356 non-null   object 
 11  희망직종경력년수        801 non-null    float64
 12  희망직종경력개월수       801 non-null    float64
 13  희망직종경력년_월수      1356 non-null   object 
 14  구직인증상태공통구분      1356 non-null   object 
 15  구직인증상태공통구분명     1356 non-null   object 
 16  등록일시            1356 non-null   object 
 17  수정일시            1356 non-null   object

In [ ]:
#중간고사 예시 1번: 서울일자리센터 데이터에서 희망직종 경력 컬럼에서 60개월 이상 경력자만 뽐으시오.
#중간고사 예시 2번 : 서울일자리센터 데이터에서 남녀 구분하여 연령대 별로 인원을 시각화 하시오.
#약간 데이터를 여러 방면으로 다룰 줄 알아야 할 듯!!